# Generated by Django 5.2.5 on 2025-08-27 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=127)),
                ('max_formula', models.CharField(blank=True, default='', max_length=255)),
                ('recovery', models.CharField(choices=[('short_rest', 'Short'), ('long_rest', 'Long'), ('daily', 'Daily')], max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('level', models.PositiveIntegerField(default=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('source', models.CharField(choices=[('race', 'Race'), ('class', 'Class'), ('item', 'Item'), ('spell', 'Spell'), ('feat', 'Feat'), ('misc', 'Misc')], max_length=16)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='stats.character')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('stat', 'Stat'), ('resource_max', 'Max'), ('flag', 'Flag')], max_length=16)),
                ('target_key', models.CharField(max_length=64)),
                ('operation', models.CharField(choices=[('add', 'Add'), ('sub', 'Sub'), ('mul', 'Mul'), ('div', 'Div'), ('set', 'Set'), ('toggle', 'Toggle')], max_length=8)),
                ('value_kind', models.CharField(choices=[('const', 'Const'), ('reference', 'Ref'), ('formula', 'Formula')], max_length=12)),
                ('value_str', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effects', to='stats.feature')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.IntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='stats.character')),
                ('resource_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='stats.resourcetype')),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('ac', 'Ac'), ('max_hp', 'Max Hp'), ('initiative', 'Init'), ('proficiency_bonus', 'Prof')], max_length=64)),
                ('base_value', models.IntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='stats.character')),
            ],
            options={
                'unique_together': {('character', 'key')},
            },
        ),
    ]
