# Generated by Django 5.2.5 on 2025-08-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_characterclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='base_ac',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='base_hp',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='character',
            name='cha_val',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='con_val',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='dex_val',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='int_val',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='speed',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='character',
            name='str_val',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='wis_val',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
